/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupArtistRouteImport } from './routes/signup.artist'
import { Route as InvoiceBookingIdRouteImport } from './routes/invoice.$bookingId'
import { Route as DashboardCustomerRouteImport } from './routes/dashboard.customer'
import { Route as DashboardArtistRouteImport } from './routes/dashboard.artist'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupArtistRoute = SignupArtistRouteImport.update({
  id: '/signup/artist',
  path: '/signup/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceBookingIdRoute = InvoiceBookingIdRouteImport.update({
  id: '/invoice/$bookingId',
  path: '/invoice/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArtistRoute = DashboardArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/$artistId',
  path: '/$artistId',
  getParentRoute: () => ArtistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/artist': typeof DashboardArtistRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/signup/artist': typeof SignupArtistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/artist': typeof DashboardArtistRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/signup/artist': typeof SignupArtistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/artist': typeof DashboardArtistRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/signup/artist': typeof SignupArtistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/dashboard'
    | '/login'
    | '/artists/$artistId'
    | '/dashboard/admin'
    | '/dashboard/artist'
    | '/dashboard/customer'
    | '/invoice/$bookingId'
    | '/signup/artist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/dashboard'
    | '/login'
    | '/artists/$artistId'
    | '/dashboard/admin'
    | '/dashboard/artist'
    | '/dashboard/customer'
    | '/invoice/$bookingId'
    | '/signup/artist'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/dashboard'
    | '/login'
    | '/artists/$artistId'
    | '/dashboard/admin'
    | '/dashboard/artist'
    | '/dashboard/customer'
    | '/invoice/$bookingId'
    | '/signup/artist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  InvoiceBookingIdRoute: typeof InvoiceBookingIdRoute
  SignupArtistRoute: typeof SignupArtistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/artist': {
      id: '/signup/artist'
      path: '/signup/artist'
      fullPath: '/signup/artist'
      preLoaderRoute: typeof SignupArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$bookingId': {
      id: '/invoice/$bookingId'
      path: '/invoice/$bookingId'
      fullPath: '/invoice/$bookingId'
      preLoaderRoute: typeof InvoiceBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customer': {
      id: '/dashboard/customer'
      path: '/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/artist': {
      id: '/dashboard/artist'
      path: '/artist'
      fullPath: '/dashboard/artist'
      preLoaderRoute: typeof DashboardArtistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
  }
}

interface ArtistsRouteChildren {
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardArtistRoute: typeof DashboardArtistRoute
  DashboardCustomerRoute: typeof DashboardCustomerRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardArtistRoute: DashboardArtistRoute,
  DashboardCustomerRoute: DashboardCustomerRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  InvoiceBookingIdRoute: InvoiceBookingIdRoute,
  SignupArtistRoute: SignupArtistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
